# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='rated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
