# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160721_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='public_post',
            field=models.BooleanField(default=True),
        ),
    ]
